/**
 * 국가코드(cntyCd) — `관세청조회코드_v1.2.xlsx` 시트「국가코드」4행 헤더·5행부터 데이터 기준으로 생성.
 * 수동 편집 대신 엑셀 갱신 후 이 파일을 재생성하세요.
 */

export type CustomsCountryId = (typeof CUSTOMS_COUNTRY_OPTIONS)[number]["id"];

export const CUSTOMS_COUNTRY_OPTIONS = [
  { id: 'AD', name: '안도라' },
  { id: 'AE', name: '아랍에미리트 연합' },
  { id: 'AF', name: '아프카니스탄' },
  { id: 'AG', name: '안티가 바부다' },
  { id: 'AI', name: '앙귈라' },
  { id: 'AL', name: '알바니아' },
  { id: 'AM', name: '아르메니아' },
  { id: 'AN', name: '네덜란드 열도' },
  { id: 'AO', name: '앙골라' },
  { id: 'AQ', name: '안타티카' },
  { id: 'AR', name: '아르헨티나' },
  { id: 'AS', name: '아메리칸 사모아' },
  { id: 'AT', name: '오스트리아' },
  { id: 'AU', name: '호주' },
  { id: 'AW', name: '아루바' },
  { id: 'AX', name: '알랜드 군도' },
  { id: 'AZ', name: '아제르바이잔' },
  { id: 'BA', name: '보스니아-헤르체고비나' },
  { id: 'BB', name: '바베이도스' },
  { id: 'BD', name: '방글라데시' },
  { id: 'BE', name: '벨기에' },
  { id: 'BF', name: '부르키나 파소' },
  { id: 'BG', name: '불가리아' },
  { id: 'BH', name: '바레인' },
  { id: 'BI', name: '부룬디' },
  { id: 'BJ', name: '베닝' },
  { id: 'BL', name: '세인트 바르탤르미' },
  { id: 'BM', name: '버뮤다' },
  { id: 'BN', name: '브루나이' },
  { id: 'BO', name: '볼리비아' },
  { id: 'BQ', name: '보네르 신트외스타티위스' },
  { id: 'BR', name: '브라질' },
  { id: 'BS', name: '바하마' },
  { id: 'BT', name: '부탄' },
  { id: 'BV', name: '보빗군도' },
  { id: 'BW', name: '보츠와나' },
  { id: 'BY', name: '벨라루스' },
  { id: 'BZ', name: '벨리제' },
  { id: 'CA', name: '캐나다' },
  { id: 'CC', name: '코스 군도' },
  { id: 'CD', name: '콩고민주공화국' },
  { id: 'CF', name: '중앙아프리카공화국' },
  { id: 'CG', name: '콩고' },
  { id: 'CH', name: '스위스' },
  { id: 'CI', name: '코트디봐르' },
  { id: 'CK', name: '쿡 아일랜드' },
  { id: 'CL', name: '칠레' },
  { id: 'CM', name: '카메룬' },
  { id: 'CN', name: '중국' },
  { id: 'CO', name: '콜롬비아' },
  { id: 'CR', name: '코스타리카' },
  { id: 'CS', name: '세르비아 와 몬테네그로' },
  { id: 'CT', name: '캔톤아일랜드' },
  { id: 'CU', name: '쿠바' },
  { id: 'CV', name: '카보 베르데' },
  { id: 'CW', name: '큐라소' },
  { id: 'CX', name: '크리스마스 아일랜드' },
  { id: 'CY', name: '사이프러스' },
  { id: 'CZ', name: '체코공화국' },
  { id: 'DE', name: '독일' },
  { id: 'DJ', name: '지부티' },
  { id: 'DK', name: '덴마크' },
  { id: 'DM', name: '도미니카' },
  { id: 'DO', name: '도미니카 공화국' },
  { id: 'DZ', name: '알제리' },
  { id: 'EC', name: '에쿠아도르' },
  { id: 'EE', name: '에스토니아' },
  { id: 'EG', name: '이집트' },
  { id: 'EH', name: '서사하라' },
  { id: 'ER', name: '에리트리아' },
  { id: 'ES', name: '스페인' },
  { id: 'ET', name: '에티오피아' },
  { id: 'EU', name: '유럽연합' },
  { id: 'FI', name: '핀란드' },
  { id: 'FJ', name: '피지' },
  { id: 'FK', name: '포클랜드 군도' },
  { id: 'FM', name: '마이크로네시아' },
  { id: 'FO', name: '파로에 군도' },
  { id: 'FR', name: '프랑스' },
  { id: 'FX', name: '프랑스 메트로폴리탄' },
  { id: 'GA', name: '가봉' },
  { id: 'GB', name: '영국' },
  { id: 'GD', name: '그레나다' },
  { id: 'GE', name: '조지아' },
  { id: 'GF', name: '불령 가이아나' },
  { id: 'GG', name: '건지' },
  { id: 'GH', name: '가나' },
  { id: 'GI', name: '지브랄타' },
  { id: 'GL', name: '그린랜드' },
  { id: 'GM', name: '감비아' },
  { id: 'GN', name: '기니' },
  { id: 'GP', name: '과델로프' },
  { id: 'GQ', name: '적도 기니' },
  { id: 'GR', name: '그리스' },
  { id: 'GS', name: '남조지아 & 남샌드위치 군도' },
  { id: 'GT', name: '과테말라' },
  { id: 'GU', name: '괌' },
  { id: 'GW', name: '기네비소' },
  { id: 'GY', name: '가이아나' },
  { id: 'HK', name: '홍콩' },
  { id: 'HM', name: '허드 앤 맥도날드 군도' },
  { id: 'HN', name: '온두라스' },
  { id: 'HR', name: '크로아티아' },
  { id: 'HT', name: '아이티' },
  { id: 'HU', name: '헝가리' },
  { id: 'ID', name: '인도네시아' },
  { id: 'IE', name: '아일랜드' },
  { id: 'IL', name: '이스라엘' },
  { id: 'IM', name: '맨섬' },
  { id: 'IN', name: '인도' },
  { id: 'IO', name: '영령 인도양' },
  { id: 'IQ', name: '이라크' },
  { id: 'IR', name: '이란' },
  { id: 'IS', name: '아이슬란드' },
  { id: 'IT', name: '이탈리아' },
  { id: 'JE', name: '저어지' },
  { id: 'JM', name: '자마이카' },
  { id: 'JO', name: '요르단' },
  { id: 'JP', name: '일본' },
  { id: 'JT', name: '존스톤 아일랜드' },
  { id: 'KE', name: '케냐' },
  { id: 'KG', name: '키르기스스탄' },
  { id: 'KH', name: '캄보디아' },
  { id: 'KI', name: '키리바티' },
  { id: 'KM', name: '코모로스' },
  { id: 'KN', name: '세인트 키츠 네비스' },
  { id: 'KP', name: '북한' },
  { id: 'KR', name: '한국' },
  { id: 'KW', name: '쿠웨이트' },
  { id: 'KY', name: '영령 캐이맨 군도' },
  { id: 'KZ', name: '카자흐스탄' },
  { id: 'LA', name: '라오스' },
  { id: 'LB', name: '레바논' },
  { id: 'LC', name: '세인트 루시아' },
  { id: 'LI', name: '리히텐슈타인' },
  { id: 'LK', name: '스리랑카' },
  { id: 'LR', name: '라이베리아' },
  { id: 'LS', name: '레소토' },
  { id: 'LT', name: '리투아니아' },
  { id: 'LU', name: '룩셈부르그' },
  { id: 'LV', name: '라트비아' },
  { id: 'LY', name: '리비아' },
  { id: 'MA', name: '모로코' },
  { id: 'MC', name: '모나코' },
  { id: 'MD', name: '몰도바' },
  { id: 'ME', name: '몬테네그로' },
  { id: 'MF', name: '세인트 마틴' },
  { id: 'MG', name: '마다카스카르' },
  { id: 'MH', name: '마샬군도' },
  { id: 'MI', name: '미드웨이 군도' },
  { id: 'MK', name: '마세도니아' },
  { id: 'ML', name: '말리' },
  { id: 'MM', name: '미얀마' },
  { id: 'MN', name: '몽골' },
  { id: 'MO', name: '마카오' },
  { id: 'MP', name: '북마리아나 군도' },
  { id: 'MQ', name: '마티니크' },
  { id: 'MR', name: '모리타니' },
  { id: 'MS', name: '몬트세라트' },
  { id: 'MT', name: '몰타' },
  { id: 'MU', name: '모리셔스' },
  { id: 'MV', name: '몰디브' },
  { id: 'MW', name: '말라위' },
  { id: 'MX', name: '멕시코' },
  { id: 'MY', name: '말레이시아' },
  { id: 'MZ', name: '모잠비크' },
  { id: 'NA', name: '나미비아' },
  { id: 'NC', name: '뉴 칼레도니아' },
  { id: 'NE', name: '니제르' },
  { id: 'NF', name: '노폴크 아일랜드' },
  { id: 'NG', name: '나이지리아' },
  { id: 'NI', name: '니카라과' },
  { id: 'NL', name: '네덜란드' },
  { id: 'NO', name: '노르웨이' },
  { id: 'NP', name: '네팔' },
  { id: 'NQ', name: '드롬힝 마우드랜드' },
  { id: 'NR', name: '나우루' },
  { id: 'NT', name: '중립지대' },
  { id: 'NU', name: '니우에' },
  { id: 'NZ', name: '뉴질랜드' },
  { id: 'OM', name: '오만' },
  { id: 'PA', name: '파나마' },
  { id: 'PE', name: '페루' },
  { id: 'PF', name: '불령 폴리네시아' },
  { id: 'PG', name: '파푸아 뉴기니' },
  { id: 'PH', name: '필리핀' },
  { id: 'PK', name: '파키스탄' },
  { id: 'PL', name: '폴란드' },
  { id: 'PM', name: '세인트 피레 미켈론' },
  { id: 'PN', name: '피트카이른' },
  { id: 'PO', name: '팔레스타인 해방기구(구)' },
  { id: 'PR', name: '푸에르토리코' },
  { id: 'PS', name: '팔레스타인 해방기구' },
  { id: 'PT', name: '포루투갈' },
  { id: 'PW', name: '팔라우' },
  { id: 'PY', name: '파라과이' },
  { id: 'PZ', name: '파나마운하지역' },
  { id: 'QA', name: '카타르' },
  { id: 'RA', name: '교포' },
  { id: 'RE', name: '불령 리유니온 코모도 제도' },
  { id: 'RK', name: '해외교포' },
  { id: 'RO', name: '루마니아' },
  { id: 'RS', name: '세르비아' },
  { id: 'RU', name: '러시아 연방' },
  { id: 'RW', name: '르완다' },
  { id: 'SA', name: '사우디아라비아' },
  { id: 'SB', name: '솔로몬 군도' },
  { id: 'SC', name: '세이쉘' },
  { id: 'SD', name: '수단' },
  { id: 'SE', name: '스웨덴' },
  { id: 'SG', name: '싱가포르' },
  { id: 'SH', name: '세인트 헬레나' },
  { id: 'SI', name: '슬로베니아' },
  { id: 'SJ', name: '스발비드 군도' },
  { id: 'SK', name: '슬로바키아' },
  { id: 'SL', name: '시에라 리온' },
  { id: 'SM', name: '산마리노' },
  { id: 'SN', name: '세네갈' },
  { id: 'SO', name: '소말리아' },
  { id: 'SR', name: '수리남' },
  { id: 'SS', name: '남수단' },
  { id: 'ST', name: '상토메 프린스페' },
  { id: 'SV', name: '엘살바도르' },
  { id: 'SX', name: '세인트마틴(생마르탱)' },
  { id: 'SY', name: '시리아' },
  { id: 'SZ', name: '스와질랜드' },
  { id: 'TC', name: '투르크 & 카이코스 군도' },
  { id: 'TD', name: '챠드' },
  { id: 'TF', name: '불령 남부지역' },
  { id: 'TG', name: '토고' },
  { id: 'TH', name: '태국' },
  { id: 'TJ', name: '타지크' },
  { id: 'TK', name: '토켈라우' },
  { id: 'TL', name: '티모르' },
  { id: 'TM', name: '투르크멘' },
  { id: 'TN', name: '튀니지' },
  { id: 'TO', name: '통가' },
  { id: 'TP', name: '티모르(구)' },
  { id: 'TR', name: '튀르키예' },
  { id: 'TT', name: '트리니다드 토바고' },
  { id: 'TV', name: '투발루' },
  { id: 'TW', name: '대만' },
  { id: 'TZ', name: '탄자니아' },
  { id: 'UA', name: '우크라이나' },
  { id: 'UG', name: '우간다' },
  { id: 'UM', name: '마이너 아우틀링 합중국 군도' },
  { id: 'US', name: '미국' },
  { id: 'UY', name: '우루과이' },
  { id: 'UZ', name: '우즈베키스탄' },
  { id: 'VA', name: '교황청' },
  { id: 'VC', name: '세인트 빈센트 그레나딘' },
  { id: 'VE', name: '베네주엘라' },
  { id: 'VG', name: '영령 버진군도' },
  { id: 'VI', name: '미령 버진군도' },
  { id: 'VN', name: '베트남' },
  { id: 'VU', name: '바누아투' },
  { id: 'WF', name: '왈라스 & 퓨투나 군도' },
  { id: 'WK', name: '웨이크 아일랜드' },
  { id: 'WS', name: '사모아' },
  { id: 'YE', name: '예맨' },
  { id: 'YM', name: '마세도니아(구)' },
  { id: 'YT', name: '메요트' },
  { id: 'YU', name: '유고' },
  { id: 'Z1', name: '국제통화기금' },
  { id: 'ZA', name: '남아프리카공화국' },
  { id: 'ZM', name: '잠비아' },
  { id: 'ZR', name: '자이르' },
  { id: 'ZW', name: '짐바브웨' },
  { id: 'ZZ', name: '기타국' },
] as const;
